sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f Dockerfile.dev .

script:
  - docker run frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-091824123864"
  bucket_path: "Frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

